#!/bin/bash
accelerate launch --config_file "deepspeed_config.yaml" peft_ds_sft_train.py \
--seed 100 \
--model_name_or_path "Qwen2.5-7B-Instruct-qlora" \
--dataset_name "sft_dataset" \
--num_train_epochs 1 \
--logging_steps 5 \
--log_level "info" \
--logging_strategy "steps" \
--save_strategy "epoch" \
--bf16 True \
--packing True \
--learning_rate 1e-4 \
--lr_scheduler_type "cosine" \
--weight_decay 1e-4 \
--warmup_ratio 0.1 \
--max_grad_norm 1.0 \
--output_dir "Qwen2.5-7B-Instruct-qlora-sft" \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 4 \
--gradient_checkpointing True \
--use_reentrant True \
--dataset_text_field "content" \
--use_flash_attn True \
--use_4bit_quantization True \
--use_nested_quant True \
--bnb_4bit_compute_dtype "bfloat16" \
--bnb_4bit_quant_storage_dtype "bfloat16"