name: qwen2.5_7b_lora_grpo

trainer:
  devices: 1  # Adjust based on available GPUs
  num_nodes: 1
  precision: bf16
  accelerator: gpu
  logger: false
  enable_checkpointing: true
  use_distributed_sampler: false
  max_epochs: 10
  max_steps: 1000  # Adjust based on your dataset size
  log_every_n_steps: 10
  val_check_interval: 100
  limit_val_batches: 50
  limit_test_batches: 50
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0

exp_manager:
  explicit_log_dir: ${name}
  exp_dir: /home/xentropy/OpenReinforcedAgent/nemo-megatron/results
  name: ${name}
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: nemo_grpo
    name: ${name}
  resume_if_exists: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 3
    mode: min
    always_save_nemo: true
    save_nemo_on_train_end: true
    filename: ${name}-{epoch:02d}-{val_loss:.3f}
    model_parallel_size: ${multiply:${model.tensor_model_parallel_size}, ${model.pipeline_model_parallel_size}}

model:
  # Model architecture
  micro_batch_size: 4  # Adjust based on GPU memory
  global_batch_size: 4  # micro_batch_size * accumulate_grad_batches * data_parallel_size
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  virtual_pipeline_model_parallel_size: null
  
  # PEFT configuration
  peft_scheme: lora  # Parameter-Efficient Fine-Tuning using LoRA
  lora_tuning:
    lora_rank: 8
    lora_alpha: 16
    lora_dropout: 0.05
    target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
    
  # GRPO configuration
  grpo:
    kl_coef: 0.1
    clip_range: 0.2
    value_clip_range: 0.2
    entropy_coef: 0.0
    normalize_advantage: true
    ref_model_path: null  # Will use the base model as reference
    
  # Tokenizer
  tokenizer:
    library: huggingface
    type: Qwen2TokenizerFast
    model_name: Qwen/Qwen2.5-7B-Instruct
    
  # Data configuration
  data:
    train_ds:
      file_path: /home/xentropy/OpenReinforcedAgent/data/train_preferences.jsonl
      global_batch_size: ${model.global_batch_size}
      micro_batch_size: ${model.micro_batch_size}
      shuffle: true
      num_workers: 2
      pin_memory: true
      max_seq_length: 2048
      
    validation_ds:
      file_path: /home/xentropy/OpenReinforcedAgent/data/val_preferences.jsonl
      global_batch_size: ${model.global_batch_size}
      micro_batch_size: ${model.micro_batch_size}
      shuffle: false
      num_workers: 2
      pin_memory: true
      max_seq_length: 2048
      
  # Optimization
  optim:
    name: adamw
    lr: 5.0e-5
    weight_decay: 0.01
    betas: [0.9, 0.999]
    sched:
      name: CosineAnnealing
      warmup_steps: 100
      constant_steps: 0
      min_lr: 5.0e-6
